# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avon', '0002_auto_20170603_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='buyer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='campaing',
            name='deperture_date',
            field=models.DateField(null=True),
        ),
    ]
