# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avon', '0003_auto_20170605_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('debt', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='buyer',
        ),
        migrations.AddField(
            model_name='article',
            name='buyer',
            field=models.ManyToManyField(to='avon.Customer'),
        ),
    ]
